### ISSUE TITLE
Refactoring during MaMiCo Coding Week February 2024

### ISSUE THREAD

**Issue by rubenhorn** [HSU-HPC/MaMiCo#39]
Branch for refactoring: [refactor2402-WIP](https://github.com/HSU-HPC/MaMiCo/tree/refactor2402-WIP)

# TODO-List:
- [x] Init load balancing @amartyads 
- [x] Rename `MacroscopicCell` to `CouplingCell` (#41) @rubenhorn 
- [x] Remove all types of legacy IndexConversion @Thinkpiet 
- [x] Refactor indexing from IndexConversion to CellIndex
  - [x] coupling/cell-mapping @LouieVoit 
  - [x] coupling/configurations @rubenhorn 
  - [x] coupling/datastructures (#43) @rubenhorn 
  - [x] coupling/filtering @Thinkpiet 
  - [x] coupling/interface @Thinkpiet 
  - [x] coupling/paralleltopology
  - [x] coupling/python-binding
  - [x] coupling/scenario
  - [x] coupling/sendrev
  - [x] coupling/services @jafariv 
  - [x] coupling/solvers
  - [x] coupling/transferstrategies
  - [x] test/integration
  - [x] test/unit
- [x] Use new CouplingCell datastructures
  - [ ] #75
