### ISSUE TITLE
Re-implement branch mpi-collective

### ISSUE THREAD

**Issue by rubenhorn** [HSU-HPC/MaMiCo#8]
The branch [mpi-collective](https://github.com/HSU-HPC/MaMiCo/tree/mpi-collective) was never merged and is way too far behind (see https://github.com/HSU-HPC/MaMiCo/compare/master...mpi-collective).
Thus, it is necessary to re-implement the features on this branch based on the current version of the master branch.

**To-Do:**
- [x] Re-implement changes from branch [mpi-collective](https://github.com/HSU-HPC/MaMiCo/tree/mpi-collective)
- [x] Test correctness of the code using simple static couette flow scenario
- [x] Test correctness of the code using dynamic scenario (adding/removing MD instances depending on error threshold)
- [ ]  Delete stale branch [mpi-collective](https://github.com/HSU-HPC/MaMiCo/tree/mpi-collective)

**Comment by amartyads** [comment]
Some clarification; reimplementing was my idea, since this branch is before the clang-tidy reformat of the whole codebase. Hence, automatic merging (which I tried) does not merge properly, I faced the same issues as back then. For example, git does not detect the large function signatures as the same, and often puts two of the same function in the same file. So I thought it's probably just easier to grab the needed code from the branch and update it in a new branch.

Unless anyone else has other ideas?

**Comment by rubenhorn** [comment]
Starting work on new branch. Track difference [here](https://github.com/HSU-HPC/MaMiCo/compare/8-re-implement-branch-mpi-collective...mpi-collective).

**Comment by rubenhorn** [comment]
### Manual test of correctness using 4 MD instances:
**MPI-collective:**
with 6a406ca3e2c1958eb875409d9d94c981 couette.xml.template
real    2m13,962s
user    8m49,738s
sys     0m2,372s

**Sequential:**
with 6a406ca3e2c1958eb875409d9d94c981 couette.xml.template
real	2m24,791s
user	9m33,096s
sys	0m1,883s

**Comparison:**
```bash
md5sum *.csv *.vtk | awk '{print $1}' > output.hash # Ignore different filenames
diff output.hashes /path/to/sequential/version/output.hashes # Finds no difference
```

**Comment by rubenhorn** [comment]
### Manual test of correctness using dynamic MD ensemble:
**MPI-collective:**
with 6a406ca3e2c1958eb875409d9d94c981 based on couette.xml.template
with `fix-seed="yes"` and `two-way-coupling="no"` (If set to `"yes"`, the values in the output start to diverge after 38 coupling cycles[^1]) and
```
number-md-simulations="dynamic"
min-number-md="4"
error-start="0.1"
error-end="0.05"
```

**Sequential:**
with 6a406ca3e2c1958eb875409d9d94c981 based on couette.xml.template
(Same change as for MPI-collective)

**Comparison:**
```bash
md5sum *.csv *.vtk | awk '{print $1}' > output.hashes # Ignore different filenames
diff output.hashes /path/to/sequential/version/output.hashes # Finds no difference
```

[^1]: The error may result from the change in how the sum of values is obtained across instances, since floating point addition is not associative (see [IEEE 754, Section 3.2](https://doi.org/10.1109/IEEESTD.2019.8766229) or the corresponding [Wikipedia article](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems))

**Comment by rubenhorn** [comment]
My suspicion is that the difference for dynamic MD ensembles is just attributable to the use of the MPI reduce operation. While [Balaji and Kimpe 2013](https://doi.org/10.1109/HPCC.and.EUC.2013.65) mention that implementors are encouraged to take care not to introduce non-determinism between runs, this does not hold for collective vs. sequential implementation.
I've been testing using OpenMPI which assumes that the reduce operations are associative according to the section [Predefined Reduce Operations](https://www.open-mpi.org/doc/v4.1/man3/MPI_Reduce.3.php#toc10) in the documentation. (This is not the case for addition of floating point numbers)
When using the collective MPI methods only for broadcasting from macro to MD, there is no divergence which would support this hypothesis.  
The coupling cycle after which a divergence of the results first occurs is also influenced by the value of the attribute `reorganise-memory-every-timestep` of the node `simulation-configuration` in the configuration, at least slightly. (Offset of 1 coupling cycle for a value of 10000000000000 instead of 20)

A visual inspection of the two versions after 50 coupling cycles using ParaView shows no discernible difference, although that is quite a weak test:
![LB_collective_mpi_48](https://github.com/HSU-HPC/MaMiCo/assets/5367484/91421bed-4fa9-47e0-94df-0c41eff1e5b4)  
![LB_master_48](https://github.com/HSU-HPC/MaMiCo/assets/5367484/98b1bd91-9a25-4036-a724-72741aadf3c7)  
The difference between both images is indicated below in pink and is completely attributable to resizing artifacts.  
![difference](https://github.com/HSU-HPC/MaMiCo/assets/5367484/b7a6075d-e55d-47e2-bd97-343811ae013f)
